### ISSUE TITLE
[DOCUMENTAÇÃO] Caso de Uso 03

### ISSUE THREAD

**Issue by Draazil** [Draazil/Source-Code-Inspection#1]
•	Severidade: Média
•	Tipo de problema: Omissão
•	Descrição: Sistema não verifica se possui notas necessarias para efetuar o troco.

•	Severidade: Baixa
•	Tipo de problema: Informação Estranha
•	Descrição: Sistema informa o saldo após a retirada do troco desnecessariamente.

**Comment by ErikItokazu** [comment]
•	Severidade: baixa
•	Tipo de problema: Omissão
•	Descrição: Quando o usuário solicita o troco e o valor é devolvido, a máquina poderia automaticamente encerrar a sessão deste usuário.

**Comment by Draazil** [comment]
Corrigido com a revisão da wiki: [dd6abda](https://github.com/Draazil/Source-Code-Inspection/wiki/Documenta%C3%A7%C3%A3o-Ticket-Machine/dd6abda1ed065807d1a6ef34c58cbe5810e9fd8a)
