### ISSUE TITLE
[DOCUMENTAÇÃO] Caso de Uso 02

### ISSUE THREAD

**Issue by Draazil** [Draazil/Source-Code-Inspection#2]
•	Severidade: Média
•	Tipo de problema: Omissão
•	Descrição: Sistema não verifica se possui papel para imprimir os bilhetes necessários.

•	Severidade: Baixa
•	Tipo de problema: 
•	Descrição:  Não há a posibilidade de se obter mais de bilhete por execução.

**Comment by ErikItokazu** [comment]
•	Severidade: Média
•	Tipo de problema: Omissão
•	Descrição: Seria muito útil e fácil que o usuário informasse quantos bilhetes ele deseja comprar e a máquina fizesse a contabilidade baseando-se no saldo, tornando o funcionamento

**Comment by Draazil** [comment]
Corrigido com a revisão da wiki: [dd6abda](https://github.com/Draazil/Source-Code-Inspection/wiki/Documenta%C3%A7%C3%A3o-Ticket-Machine/dd6abda1ed065807d1a6ef34c58cbe5810e9fd8a)
