### ISSUE TITLE
[DOCUMENTAÇÃO] Caso de Uso 01

### ISSUE THREAD

**Issue by ErikItokazu** [Draazil/Source-Code-Inspection#3]
•	Severidade: Alta
•	Tipo de problema: Omissão
•	Descrição:A máquina aceita qualquer nota/valor de papel-moeda? Ou ela aceita apenas determinadas notas de determinados valores?

**Comment by Draazil** [comment]
Corrigido com a revisão da wiki: [dd6abda](https://github.com/Draazil/Source-Code-Inspection/wiki/Documenta%C3%A7%C3%A3o-Ticket-Machine/dd6abda1ed065807d1a6ef34c58cbe5810e9fd8a)
